In [3]:
#Count Vect
#Bag of words
#Model Build

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('SMSSpamCollection',names=["label", "message"], sep='\t')
df

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
df['label'].value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [7]:
df['Spam']=df.label

In [8]:
df.Spam.replace({'ham':0,'spam':1},inplace=True)
df.head()

label                                            message  Spam
0   ham  Go until jurong point, crazy.. Available only ...     0
1   ham                      Ok lar... Joking wif u oni...     0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3   ham  U dun say so early hor... U c already then say...     0
4   ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()
cv_matrix=cv.fit_transform(df.message)
cv_matrix=cv_matrix.toarray()

cv_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [10]:
cv.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [11]:
cv.get_feature_names_out().shape

(8713,)

In [12]:
cv.vocabulary_

{'go': 3571,
 'until': 8084,
 'jurong': 4374,
 'point': 5958,
 'crazy': 2338,
 'available': 1316,
 'only': 5571,
 'in': 4114,
 'bugis': 1767,
 'great': 3655,
 'world': 8548,
 'la': 4501,
 'buffet': 1765,
 'cine': 2061,
 'there': 7694,
 'got': 3615,
 'amore': 1082,
 'wat': 8324,
 'ok': 5538,
 'lar': 4537,
 'joking': 4342,
 'wif': 8450,
 'oni': 5567,
 'free': 3373,
 'entry': 2963,
 'wkly': 8506,
 'comp': 2178,
 'to': 7806,
 'win': 8463,
 'fa': 3100,
 'cup': 2398,
 'final': 3221,
 'tkts': 7793,
 '21st': 412,
 'may': 4959,
 '2005': 403,
 'text': 7644,
 '87121': 794,
 'receive': 6340,
 'question': 6232,
 'std': 7279,
 'txt': 7986,
 'rate': 6284,
 'apply': 1169,
 '08452810075over18': 77,
 'dun': 2815,
 'say': 6679,
 'so': 7074,
 'early': 2836,
 'hor': 3952,
 'already': 1054,
 'then': 7688,
 'nah': 5270,
 'don': 2724,
 'think': 7709,
 'he': 3805,
 'goes': 3579,
 'usf': 8130,
 'lives': 4692,
 'around': 1220,
 'here': 3856,
 'though': 7729,
 'freemsg': 3380,
 'hey': 3866,
 'darling': 2455,
 'it

In [13]:
cv.get_feature_names_out()[2050]

'chores'

In [14]:
cv_matrix.shape

(5572, 8713)

In [15]:
cv_matrix[0]

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
np.where(cv_matrix[0]!=0)

(array([1082, 1316, 1765, 1767, 2061, 2338, 3571, 3615, 3655, 4114, 4374,
        4501, 5571, 5958, 7694, 8084, 8324, 8548]),)

In [17]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(cv_matrix,df.Spam,test_size=0.2)

In [18]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()
model.fit(X_train,Y_train)

MultinomialNB()

In [19]:
model.score(X_train,Y_train)

0.9930446488669509

In [20]:
y_pred=model.predict(X_test)

In [21]:
from sklearn.metrics import classification_report

cr=classification_report(Y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       957
           1       0.91      0.97      0.94       158

    accuracy                           0.98      1115
   macro avg       0.95      0.98      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [23]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]


cvv=cv.transform(emails)
model.predict(cvv)

array([0, 1])

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
import csv
from sklearn.metrics import classification_report

In [33]:
#df=pd.read_csv('IMDB Dataset.csv',delimiter='\t',names=['Review','Sentiment'],quoting=csv.QUOTE_NONE, quotechar='"',encoding='utf8',on_bad_lines='skip')
#df

Review Sentiment
0                                       review,sentiment       NaN
1      "One of the other reviewers has mentioned that...       NaN
2      "A wonderful little production. <br /><br />Th...       NaN
3      "I thought this was a wonderful way to spend t...       NaN
4      "Basically there's a family where a little boy...       NaN
...                                                  ...       ...
12633  "This version of the Charles Dickens novel fea...       NaN
12634  "Despite the fact that he worked for the worst...       NaN
12635  "this is the worst film I've seen in a long lo...       NaN
12636  "I saw this movie when it was broadcast on tel...       NaN
12637  "While Bondarchuk was by no means a young man ...       NaN

[12638 rows x 2 columns]