In [13]:
# Embeddings
# pad sequences

In [32]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Flatten,Dropout,Embedding

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [33]:

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [34]:
# OHE

vocab_size=30
rev=[one_hot(i,vocab_size) for i in reviews]
rev

[[20, 12],
 [15, 8],
 [12, 8],
 [6, 26, 12],
 [26, 26, 17],
 [12, 12],
 [2, 26, 6],
 [2, 15],
 [2, 12],
 [28, 7]]

In [35]:
max_length=3
pad_review=pad_sequences(rev,maxlen=max_length,padding='post')
print(pad_review)

[[20 12  0]
 [15  8  0]
 [12  8  0]
 [ 6 26 12]
 [26 26 17]
 [12 12  0]
 [ 2 26  6]
 [ 2 15  0]
 [ 2 12  0]
 [28  7  0]]


In [36]:
Embedding_size=5

model=Sequential([
    Embedding(vocab_size,Embedding_size,input_length=max_length,name="embedding"),
    Flatten(),
    Dense(1,'softmax')
])


In [37]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten_4 (Flatten)         (None, 15)                0         
                                                                 
 dense_4 (Dense)             (None, 1)                 16        
                                                                 
Total params: 166 (664.00 Byte)
Trainable params: 166 (664.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [51]:
#from sklearn.preprocessing import MinMaxScaler

#scaler = MinMaxScaler()
#normalized_data = scaler.fit_transform(pad_review)


In [56]:
model.fit(pad_review, sentiment, epochs=50, verbose=0)

In [57]:
loss, accuracy = model.evaluate(pad_review, sentiment)
accuracy

1/1 [==============================] - 0s 29ms/step - loss: 0.6931 - accuracy: 0.5000


0.5

In [58]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30